kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vz-test-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "virtuozzo-storage"
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
